package com.example.demo.bean;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table picture
 */
public class Picture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.image
     *
     * @mbg.generated
     */
    private String image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.pid
     *
     * @return the value of picture.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.pid
     *
     * @param pid the value for picture.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.image
     *
     * @return the value of picture.image
     *
     * @mbg.generated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.image
     *
     * @param image the value for picture.image
     *
     * @mbg.generated
     */
    public void setImage(String image) {
        this.image = image;
    }
}