spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentsystem?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC #url
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.bean

server:
  port: 8081
