spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dump?useSSL=false #url
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.demo.bean

