package com.example.demo.mapper;

import com.example.demo.bean.Browse;
import com.example.demo.bean.BrowseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BrowseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbg.generated
     */
    long countByExample(BrowseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbg.generated
     */
    int deleteByExample(BrowseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbg.generated
     */
    int insert(Browse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbg.generated
     */
    int insertSelective(Browse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbg.generated
     */
    List<Browse> selectByExample(BrowseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbg.generated
     */
    Browse selectByPrimaryKey(Integer bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Browse record, @Param("example") BrowseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Browse record, @Param("example") BrowseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Browse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Browse record);
}